### ISSUE TITLE
I can't submit a token on the Website.

### ISSUE THREAD

**Issue by Repaler** [Livaco/website-issues#4]
it just complains that there is an SQL syntax error backend

**Comment by Livaco** [comment]
Can you copy and paste the SQL error, and where in the ticket creation process this happens? Once again sorry for taking so long to get back to you.

**Comment by Livaco** [comment]
Do you mean Ticket? Also can you copy and paste the SQL error and where in the process it happens? Thanks!

**Comment by Livaco** [comment]
@Repaler ?

**Comment by Livaco** [comment]
Going to close this since I'm still getting support tickets fine and it seems i'm getting nothing back.
